/** Auto-generated by scripts/write-bundle-identity.mjs — do not edit. */
export const BUNDLE_IDENTITY = {
  branch: "cursor/fix-bundle-regression-e67e",
  commit: "913dfd668",
  builtAt: "2026-07-19T10:32:41.882Z",
} as const;
