/** Auto-generated by scripts/write-bundle-identity.mjs — do not edit. */
export const BUNDLE_IDENTITY = {
  branch: "cursor/fix-bundle-regression-e67e",
  commit: "4962596f4",
  builtAt: "2026-07-19T10:31:12.820Z",
} as const;
