import { Router, type IRouter } from "express";
import healthRouter from "./health";
import oddsRouter from "./odds";
import propsRouter from "./props";
import gamesRouter from "./games";
import injuriesRouter from "./injuries";
import weatherRouter from "./weather";
import chatRouter from "./chat";
import athletesRouter from "./athletes";
import historyRouter from "./history";
import defenseRouter from "./defense";
import teamPeriodStatsRouter from "./teamPeriodStats";
import mlbRouter from "./mlb";
import statmuseRouter from "./statmuse";
import bballrefRouter from "./bballref";
import slipImageRouter from "./slipImage";
import syncRouter from "./sync";
import ufcRouter from "./ufc";
import tennisRouter from "./tennis";
import notificationsRouter from "./notifications";
import gradeRouter from "./grade";

const router: IRouter = Router();

router.use(healthRouter);
router.use(oddsRouter);
router.use(propsRouter);
router.use(gamesRouter);
router.use(injuriesRouter);
router.use(weatherRouter);
router.use(chatRouter);
router.use(athletesRouter);
router.use(historyRouter);
router.use(defenseRouter);
router.use(teamPeriodStatsRouter);
router.use(mlbRouter);
router.use(statmuseRouter);
router.use(bballrefRouter);
router.use(slipImageRouter);
router.use(syncRouter);
router.use(ufcRouter);
router.use(tennisRouter);
router.use(notificationsRouter);
router.use(gradeRouter);

export default router;
